# Generated by Django 5.2.6 on 2025-09-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendancerecord_schedule_and_more'),
        ('attendance', '0003_add_default_locations'),
    ]

    operations = [
    ]
