# Generated by Django 5.2.6 on 2025-09-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='location',
            field=models.CharField(default='insert location', max_length=100),
        ),
    ]
