# Generated by Django 5.2.6 on 2025-09-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.location'),
        ),
    ]
