# Generated by Django 5.2.6 on 2025-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendancerecord_location'),
        ('attendance', '0009_add_location_field'),
    ]

    operations = [
    ]
