# Generated by Django 5.2.6 on 2025-09-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_merge_20250924_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='webauthn_credential_id',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='webauthn_public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='webauthn_sign_count',
            field=models.IntegerField(default=0),
        ),
    ]
