# Generated by Django 5.2.6 on 2025-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_student_webauthn_credential_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='webauthn_sign_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
